project:
  type: book
book:
  title: "OpenIVIS Summer 2024 Report"
  author:
    - name: Hailey Knolton
      email: hknolton@g.hmc.edu
    - name: Ruby Peterman
      email: rpeterman@g.hmc.edu


  date: 2024-07-11
  chapters:
    - index.qmd
    - sections/abstract/abstract.qmd
    - sections/introduction/introduction.qmd
    - sections/methods/methods.qmd
    - sections/results/results.qmd
    - sections/conclusion/conclusion.qmd
    - sections/acknowledgements/acknowledgements.qmd
    - sections/appendix/appendix.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    number-sections: true
    toc: true
    toc-depth: 4
  pdf: default

bibliography: references.bib
csl: ieee.csl




